extend-include = ["__init__.py"]
exclude = ["scroll_frame.py", "tooltip.py"]
line-length = 160

[lint]
select = [
  "ANN",
  "ARG",
  "E",
  "F",
  "I",
  "N",
  "Q",
  "W",
]

ignore = [
  "ANN002",
  "ANN003",
  "E501",
]
